apiVersion: v1
description: A Helm chart to install Argo-Events in k8s Cluster
name: argo-events
version: 0.17.0
keywords:
  - argo-events
  - sensor-controller
  - eventsource-controller
  - eventbus-controller
sources:
  - https://github.com/argoproj/argo-events
maintainers:
  - name: Vaibhav Page
  - name: Derek Wang
appVersion: 0.17.0
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
